language: node_js
node_js:
  - "14"
script: yarn build
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: blergatron
  on:
    all_branches: true
